language: node_js

node_js:
  - "10"

stages:
  - name: lint
    if: NOT tag =~ /^v\d+\.\d+$/
  - name: build
    if: branch = master AND tag = /^v\d+\.\d+$/

jobs:
  include:
    - stage: lint
      script: yarn run test
    - stage: build
      script: yarn run build
