language: node_js

node_js:
  - "10"

stages:
  - test
    if: NOT tag =~ /^v\d+\.\d+$/
  - build
    if: branch = master AND tag = /^v\d+\.\d+$/

jobs:
  include:
    - stage:test
      script:
        - yarn run test
    - stage:build
      script:
        - yarn run build
