name: Action CI

on:
  push:
    branches:
      - master
      - release
env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup nodejs
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - name: Install
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test --coverage
      - name: Codecov
        run: yarn codecov -t $CODECOV_TOKEN
